name: An Introduction to Python Programming
category: coding
authors: ""
shortdesc: This course will introduce more intermediate features of Python that are useful for biomolecular modellers.
longdesc: ""
